interval:
  autoSettleBufferTime: 60
  forceSettlementProcessor: 600
  settlementProcessor: 300
networks:
  ethereum0g:
    url: "https://evmrpc-testnet.0g.ai"
    chainID: 16600
    privateKeys:
      - 7d345cf3ac4b04f3edb41246ede598ec25ff424bd61d5b7a61d04be0b03ab154
    transactionLimit: 1000000
    gasEstimationBuffer: 10000
service:
  servingUrl: "83.144.23.154:8080"
  targetUrl: "http://localhost:8000/v1/fact-check"
  inputPrice: 1
  outputPrice: 1
  type: "chatbot"
  model: "bart"
  verifiability: "TeeML"

